# Site settings
title: Lena Popova Photography
email: popovapictures@gmail.com
description: "Photo portfolio for Lena Popova"
twitter_username: popovaphotography
github_username:  denipo
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
