# Site settings
title: Lena Popova Photography
email: popovapictures@gmail.com
description: "Photo portfolio for Lena Popova"
twitter_username: popovaphotography
github_username:  denipo
baseurl: "lena.popova.photo"

# Build settings
markdown: kramdown
permalink: pretty
